### PR TITLE
Change license to BSD 3 Clause and add DCO file

### PR DESCRIPTION
**Pull request by dledford**
As per the Oct. 20, 2023 OFMF Working Group meeting, the BSD 3 Clause license and Developer Certificate of Origin certification were deemed most appropriate for this repository. This updates the repository before we start adding new code.

Signed-off-by: Doug Ledford <dledford@redhat.com>

### CODE REVIEW

**Review by christian-pinto — APPROVED** [review]
LGTM

**Review by mgazz — APPROVED** [review]
LGTM

**Comment by christian-pinto** [comment]
@dledford, please sign your commits. Thanks

**Review by christian-pinto — CHANGES_REQUESTED** [review]
@dledford , please sign your commits. Thanks

**Comment by dledford** [comment]
> @dledford , please sign your commits. Thanks

@christian-pinto I changed the repo rules to not require signed commits (when it refers to signed commits, it doesn't mean signed with Signed-off-by:, which my commits already had, it means GPG signed commits, which I'm not sure we want to require on the repos as that might be too heavy weight for the average contributor that might not have a GPG key already setup and ready to go).

**Comment by christian-pinto** [comment]
> > @dledford , please sign your commits. Thanks
> 
> @christian-pinto I changed the repo rules to not require signed commits (when it refers to signed commits, it doesn't mean signed with Signed-off-by:, which my commits already had, it means GPG signed commits, which I'm not sure we want to require on the repos as that might be too heavy weight for the average contributor that might not have a GPG key already setup and ready to go).

Yep yep. I knew it meant signed with the GPG key. Fine by me. Merging

**Review by christian-pinto — APPROVED** [review]
All good now!

**Pull request merged**
